---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  entries:
  - title: SAP ソリューション
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: FlexPod SAP ソリューション
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: ネットアップのソリューション
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: 法的通知
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: 設定のベストプラクティス
    links:
    - title: デモビデオ
      url: sap-bp-videos.html
    - title: ブログ
      url: sap-bp-blogs.html
    - title: ツール
      url: sap-bp-tools.html
  - title: バックアップ、リストア、ディザスタリカバリ
    links:
    - title: デモビデオ
      url: sap-dr-videos.html
    - title: ブログ
      url: sap-dr-blogs.html
    - title: ツール
      url: sap-dr-tools.html
  - title: ライフサイクル管理
    links:
    - title: デモビデオ
      url: sap-lcm-videos.html
    - title: ブログ
      url: sap-lcm-blogs.html
    - title: ツール
      url: sap-lcm-tools.html
  - title: すべての SAP ソリューション
    links:
    - title: 新機能
      url: sap-whatsnew.html
    - title: デモビデオ
      url: sap-videos.html
    - title: ブログ
      url: sap-blogs.html
