---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: SAP ソリューション
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: FlexPod SAP ソリューション
    url: https://docs.netapp.com/us-en/flexpod/ent-db/index.html
  - title: ネットアップのソリューション
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: 法的通知
    url: "/reference_legal_notices.html"
