---
settings:
  name: NetApp Solutions SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: ja-jp,us-en,zh-cn
sidebar:
  entries:
  - title: SAP ソリューション
    url: "/index.html"
  - section: bp
  - section: backup
  - section: lifecycle
  - section: briefs
  - title: ネットアップのソリューション
    url: https://docs.netapp.com/us-en/netapp-solutions/
  - title: 法的通知
    url: "/reference_legal_notices.html"
