---
sidebar: sidebar 
permalink: backup/anf-cba-overview.html 
keywords: tr4959, 4959, overview, introduction 
summary: このテクニカルレポートでは、NetApp BlueXP Cloud Backup for Applications（CBA）を使用したAzure NetApp Files （ANF）でのSAP HANAデータ保護のベストプラクティスを紹介します。このドキュメントでは、CBAの概念、構成のベストプラクティス、およびバックアップおよびリストア/リカバリ処理の処理ワークフローについて説明します。 
---
= TR-4959：『SAP HANA on ANF - Backup and recovery with Cloud Backup for Applications』
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


ネットアップ Nils Bauer

[role="lead"]
このテクニカルレポートでは、NetApp BlueXP Cloud Backup for Applications（CBA）を使用したAzure NetApp Files （ANF）でのSAP HANAデータ保護のベストプラクティスを紹介します。このドキュメントでは、CBAの概念、構成のベストプラクティス、およびバックアップおよびリストア/リカバリ処理の処理ワークフローについて説明します。

今日の企業には、 SAP アプリケーションを中断なく継続的に利用できることが求められています。データ量の増加や、システムバックアップなどの日常的な保守タスクに直面しても、一貫したパフォーマンスレベルを期待しています。SAP データベースのバックアップは重要な作業であり、本番用 SAP システムのパフォーマンスに大きく影響する可能性があります。

バックアップウィンドウは短くなっている一方で、バックアップするデータの量は増え続けています。したがって、ビジネスプロセスへの影響を最小限に抑えながらバックアップを実行できる時間を見つけることは困難です。本番環境と非本番環境のSAPシステムのダウンタイムは、ビジネスコストを削減するために最小化する必要があるため、SAPシステムのリストアとリカバリに要する時間は重要です。

link:anf-cba-backup-and-recovery-using-azure-netapp-files.html["次の記事：Azure NetApp Files を使用したバックアップとリカバリ"]
