---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup.html 
keywords: multipathing, fcp, hba, configure 
summary: ホストをセットアップする前に、ネットアップサポートサイトから NetApp SAN Host Utilities をダウンロードし、 HANA サーバにインストールしておく必要があります。ホスト・ユーティリティのマニュアルには、使用する FCP HBA に応じてインストールする必要がある追加ソフトウェアの情報が記載されています。 
---
= ホストのセットアップ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ホストをセットアップする前に、 NetApp SAN Host Utilities をからダウンロードしておく必要があります http://mysupport.netapp.com/["ネットアップサポート"^] HANA サーバにインストールします。ホスト・ユーティリティのマニュアルには、使用する FCP HBA に応じてインストールする必要がある追加ソフトウェアの情報が記載されています。

また、使用している Linux バージョンに固有のマルチパス構成に関する情報も記載されています。このドキュメントでは、 SLES 12 SP1 以降および RHEL 7 で必要な設定手順について説明します。2 以降。を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["『 Linux Host Utilities 7.1 Installation and Setup Guide 』"^]。



=== マルチパスを設定します


NOTE: SAP HANA マルチホスト構成のすべてのワーカーホストとスタンバイホストで、手順 1~6 を実行する必要があります。

マルチパスを設定するには、次の手順を実行します。

. 各サーバで Linux の「 re scan-scsi-bus.sh -a' 」コマンドを実行して、新しい LUN を検出します。
. 実行 `sanlun lun show`コマンドを実行し、必要なLUNがすべて表示されていることを確認します。次の例は、  `sanlun lun show` 2つのデータLUNと2つのログLUNを持つ2+1マルチホストHANAシステムのコマンド出力。出力には、LUNと対応するデバイスファイル（LUNなど）が表示されます。  `FC5_data_mnt00001`デバイスファイル `/dev/sdag`各 LUN には、ホストからストレージ コントローラへの FC パスが 8 つあります。
+
....
sapcc-hana-tst:~ # sanlun lun show
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
---------------------------------------------------------------------------------------------------------------
svm1                          FC5_log2_mnt00002              /dev/sdbb       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdba       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaz       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sday       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdax       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdaw       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdav       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdau       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdat       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdas       host21     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdar       host21     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaq       host21     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdap       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdao       host21     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdan       host21     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdam       host21     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdal       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdak       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdaj       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdai       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdah       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdag       host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdaf       host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdae       host20     FCP        1t      cDOT
svm1                          FC5_log2_mnt00002              /dev/sdad       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00002               /dev/sdac       host20     FCP        500g    cDOT
svm1                          FC5_log2_mnt00001              /dev/sdab       host20     FCP        500g    cDOT
svm1                          FC5_log_mnt00001               /dev/sdaa       host20     FCP        500g    cDOT
svm1                          FC5_data2_mnt00002             /dev/sdz        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00002              /dev/sdy        host20     FCP        1t      cDOT
svm1                          FC5_data2_mnt00001             /dev/sdx        host20     FCP        1t      cDOT
svm1                          FC5_data_mnt00001              /dev/sdw        host20     FCP        1t      cDOT

....
. 実行 `multipath -r`そして `multipath -ll`デバイス ファイル名のワールドワイド識別子 (WWID) を取得するコマンド。
+

NOTE: この例では、8 つの LUN があります。

+
....
sapcc-hana-tst:~ # multipath -r
sapcc-hana-tst:~ # multipath -ll
3600a098038314e63492b59326b4b786d dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
3600a098038314e63492b59326b4b786e dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
3600a098038314e63492b59326b4b786f dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
3600a098038314e63492b59326b4b7870 dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
3600a098038314e63532459326d495a64 dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
3600a098038314e63532459326d495a65 dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
3600a098038314e63532459326d495a66 dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
3600a098038314e63532459326d495a67 dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....
. /etc/multipath.conf ファイルを編集し 'WWID とエイリアス名を追加します
+

NOTE: 出力例は '2+1 マルチホスト・システムの 4 つの LUN のエイリアス名を含む /etc/multipath.conf ファイルの内容を示しています使用可能な multipath.conf ファイルがない場合、「 multipath-T 」 /etc/multipath.conf を実行して作成できます。

+
....
sapcc-hana-tst:/ # cat /etc/multipath.conf
multipaths {
                multipath {
                wwid    3600a098038314e63492b59326b4b786d
                alias   svm1-FC5_data2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786e
                alias   svm1-FC5_data2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a64
                alias   svm1-FC5_data_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a65
                alias   svm1-FC5_data_mnt00002
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b786f
                alias   svm1-FC5_log2_mnt00001
        }
        multipath {
                wwid    3600a098038314e63492b59326b4b7870
                alias   svm1-FC5_log2_mnt00002
        }
        multipath {
                wwid    3600a098038314e63532459326d495a66
                alias   svm1-FC5_log_mnt00001
        }
        multipath {
                wwid    3600a098038314e63532459326d495a67
                alias   svm1-FC5_log_mnt00002
        }


}
....
. 「 multipath -r 」コマンドを実行して、デバイスマップをリロードします。
. すべての LUN 、エイリアス名、およびアクティブパスとスタンバイパスを一覧表示するには、「マルチパス -ll 」コマンドを実行して構成を確認します。
+

NOTE: 次の出力例は、 2 つのデータ LUN と 2 つのログ LUN を持つ 2+1 マルチホスト HANA システムの出力を示しています。

+
....
sapcc-hana-tst:~ # multipath -ll
hsvm1-FC5_data2_mnt00001 (3600a098038314e63492b59326b4b786d) dm-7 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:2 sdaf 65:240 active ready running
  |- 20:0:5:2 sdx  65:112 active ready running
  |- 21:0:4:2 sdav 66:240 active ready running
  `- 21:0:6:2 sdan 66:112 active ready running
svm1-FC5_data2_mnt00002 (3600a098038314e63492b59326b4b786e) dm-9 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:4 sdah 66:16  active ready running
  |- 20:0:5:4 sdz  65:144 active ready running
  |- 21:0:4:4 sdax 67:16  active ready running
  `- 21:0:6:4 sdap 66:144 active ready running
svm1-FC5_data_mnt00001 (3600a098038314e63532459326d495a64) dm-6 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:1 sdae 65:224 active ready running
  |- 20:0:5:1 sdw  65:96  active ready running
  |- 21:0:4:1 sdau 66:224 active ready running
  `- 21:0:6:1 sdam 66:96  active ready running
svm1-FC5_data_mnt00002 (3600a098038314e63532459326d495a65) dm-8 NETAPP,LUN C-Mode
size=1.0T features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:3 sdag 66:0   active ready running
  |- 20:0:5:3 sdy  65:128 active ready running
  |- 21:0:4:3 sdaw 67:0   active ready running
  `- 21:0:6:3 sdao 66:128 active ready running
svm1-FC5_log2_mnt00001 (3600a098038314e63492b59326b4b786f) dm-11 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:6 sdaj 66:48  active ready running
  |- 20:0:5:6 sdab 65:176 active ready running
  |- 21:0:4:6 sdaz 67:48  active ready running
  `- 21:0:6:6 sdar 66:176 active ready running
svm1-FC5_log2_mnt00002 (3600a098038314e63492b59326b4b7870) dm-13 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:8 sdal 66:80  active ready running
  |- 20:0:5:8 sdad 65:208 active ready running
  |- 21:0:4:8 sdbb 67:80  active ready running
  `- 21:0:6:8 sdat 66:208 active ready running
svm1-FC5_log_mnt00001 (3600a098038314e63532459326d495a66) dm-10 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:5 sdai 66:32  active ready running
  |- 20:0:5:5 sdaa 65:160 active ready running
  |- 21:0:4:5 sday 67:32  active ready running
  `- 21:0:6:5 sdaq 66:160 active ready running
svm1-FC5_log_mnt00002 (3600a098038314e63532459326d495a67) dm-12 NETAPP,LUN C-Mode
size=500G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 20:0:4:7 sdak 66:64  active ready running
  |- 20:0:5:7 sdac 65:192 active ready running
  |- 21:0:4:7 sdba 67:64  active ready running
  `- 21:0:6:7 sdas 66:192 active ready running

....

