---
sidebar: sidebar 
permalink: bp/hana-asa-fc-storage-controller-setup_multiple_hosts.html 
keywords: storage efficiency, netapp volume encryption, quality of service, qos, fabricpool, Disk shelf, sas, fcp port sets, linux lvm, 
summary: このセクションでは、複数のホストシステム用のLUNを作成する方法について説明します。 
---
= ストレージコントローラのセットアップ - 複数のホスト
:allow-uri-read: 




== ストレージコントローラのセットアップ - 複数のホスト

[role="lead"]
このセクションでは、SAP HANAマルチホストシステムに固有のNetAppストレージシステムの構成について説明します。



== SAP HANA マルチホストシステムの LUN 構成

Linux LVM は、パフォーマンスを向上し、LUN サイズの制限に対処するために使用されています。

次の表に示すように、 SAP HANA ホストで、ボリュームグループと論理ボリュームを作成してマウントする必要があります。

|===
| 論理ボリューム（LV） | SAP HANA ホストのマウントポイント | 注 


| lv ： FC5_data_mnt00001 -vol | /hana/data FC5/mnt00001 のように指定します | ストレージコネクタを使用してマウント 


| lv ： FC5_log_mnt00001 -vol | /hana/log/FC5/mnt00001 | ストレージコネクタを使用してマウント 


| lv ： FC5_data_mnt00002 -vol | /hana/data FC5/mnt00002 のように指定します | ストレージコネクタを使用してマウント 


| lv ： FC5_log_mnt00002 -vol | /hana/log/FC5/mnt00002 | ストレージコネクタを使用してマウント 


| 外部NFS共有: FC5_shared | /hana/shared にアクセスします | NFS と /etc/fstab のエントリを使用して、すべてのホストにマウントされます 
|===

NOTE: SAP HANAマルチホストシステムでは、  `/hana/shared`システムのすべてのホストに接続されたファイルシステム。通常、これはNFSサーバーによって提供されるNFS共有です。NetAppFASやAFFシステムなどの高可用性NFSサーバーの使用をお勧めします。また、Linuxホストに内蔵されているNFSサーバーを使用することもできます。


NOTE: 説明した構成では、  `/usr/sap/FC5`ユーザーFC5admのデフォルトのホームディレクトリが格納されているディレクトリは、各HANAホストのローカルディスク上にあります。ディスクベースのレプリケーションによる災害復旧設定では、NetAppは4つの追加LUNを使用することを推奨しています。  `/usr/sap/FC5`各ホストにファイルシステムを配置して、各データベース ホストのすべてのファイルシステムが中央ストレージ上に存在するようにします。



== LUN の作成とイニシエーター グループへの LUN のマッピング

NetApp ONTAP System Managerを使用してストレージボリュームとLUNを作成し、それらをサーバとONTAP CLIのigroupにマッピングすることができます。このマニュアルでは、CLIの使用方法について説明します。


NOTE: 「 anlun 」ツールは NetApp Host Utilities の一部であり、各 SAP HANA ホストにインストールする必要があります。詳細については、「 host_setup 」セクションを参照してください。



=== CLI を使用して LUN を作成し、LUN をイニシエータ グループにマッピングする

このセクションでは、LVM を使用し、LVM ボリューム グループごとに 2 つの LUN を持つ FC5 を備えた 2+1 SAP HANA マルチホスト システムに対して ONTAP 9 のコマンド ラインを使用した構成例を示します。

. すべての LUN を作成します。
+
....
lun create -path FC5_data_mnt00001   -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00001 -size 1t -ostype linux  -class regular
lun create -path FC5_data_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_data2_mnt00002 -size 1t -ostype linux  -class regular
lun create -path FC5_log_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00001 -size 260g -ostype linux  -class regular
lun create -path FC5_log_mnt00002 -size 260g -ostype linux  -class regular
lun create -path FC5_log2_mnt00002 -size 260g -ostype linux  -class regular
....
. システム FC5 に属するすべてのサーバのイニシエータグループを作成します。
+
....
lun igroup create -igroup HANA-FC5 -protocol fcp -ostype linux -initiator 10000090fadcc5fa,10000090fadcc5fb,10000090fadcc5c1,10000090fadcc5c2,10000090fadcc5c3,10000090fadcc5c4 -vserver svm1
....
. 作成したイニシエータグループにすべての LUN をマッピングします。
+
....
lun map -path FC5_data_mnt00001  -igroup HANA-FC5
lun map -path FC5_data2_mnt00001  -igroup HANA-FC5
lun map -path FC5_data_mnt00002  -igroup HANA-FC5
lun map -path FC5_data2_mnt00002  -igroup HANA-FC5
lun map -path FC5_log_mnt00001  -igroup HANA-FC5
lun map -path FC5_log2_mnt00001  -igroup HANA-FC5
lun map -path FC5_log_mnt00002  -igroup HANA-FC5
lun map -path FC5_log2_mnt00002  -igroup HANA-FC5
....

