---
sidebar: sidebar 
permalink: bp/hana-asa-fc-host-setup_single.html 
keywords: multipathing, fcp, hba, configure 
summary: ホストをセットアップする前に、ネットアップサポートサイトから NetApp SAN Host Utilities をダウンロードし、 HANA サーバにインストールしておく必要があります。ホスト・ユーティリティのマニュアルには、使用する FCP HBA に応じてインストールする必要がある追加ソフトウェアの情報が記載されています。 
---
= 単一ホスト設定
:allow-uri-read: 




== 単一ホスト設定

[role="lead"]
この章では、SAP HANA 単一ホストのセットアップについて説明します。



== SAP HANA 単一ホストシステムの LUN 構成

Linux LVM は、パフォーマンスを向上し、LUN サイズの制限に対処するために使用されています。次の表に示すように、 SAP HANA ホストで、ボリュームグループと論理ボリュームを作成してマウントする必要があります。

|===
| 論理ボリューム / LUN | SAP HANA ホストのマウントポイント | 注 


| lv ： FC5_data_mnt00001 -vol | /hana/data FC5/mnt00001 のように指定します | /etc/fstab エントリを使用してマウントされます 


| lv ： FC5_log_mnt00001 -vol | /hana/log/FC5/mnt00001 | /etc/fstab エントリを使用してマウントされます 


| LUN：FC5_shared | /hana/shareed/FC5 | /etc/fstab エントリを使用してマウントされます 
|===

NOTE: 説明した構成では、  `/usr/sap/FC5`ユーザFC5admのデフォルトのホームディレクトリが格納されているディレクトリは、ローカルディスク上にあります。ディスクベースのレプリケーションによる災害復旧設定では、NetAppは、  `/usr/sap/FC5`すべてのファイルシステムが中央ストレージ上に存在するようにディレクトリを作成します。



=== LVM ボリュームグループと論理ボリュームを作成

. すべての LUN を物理ボリュームとして初期化します。
+
....
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_data_mnt00001_2
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_1
pvcreate /dev/mapper/svm1-FC5_log_mnt00001_2
....
. 各データパーティションとログパーティションのボリュームグループを作成します。
+
....
vgcreate FC5_data_mnt00001 /dev/mapper/svm1-FC5_data_mnt00001_1 /dev/mapper/svm1-FC5_data_mnt00001_2
vgcreate FC5_log_mnt00001 /dev/mapper/svm1-FC5_log_mnt00001_1 /dev/mapper/svm1-FC5_log_mnt00001_2
....
. データパーティションとログパーティションごとに論理ボリュームを作成します。ボリュームグループごとに使用されている LUN の数（この例では 2 つ）と同じストライプサイズを使用し、データの場合は 256K 、ログの場合は 64k を使用します。SAP では、ボリュームグループごとに 1 つの論理ボリュームのみがサポートされます。
+
....
lvcreate --extents 100%FREE -i 2 -I 256k --name vol FC5_data_mnt00001
lvcreate --extents 100%FREE -i 2 -I 64k --name vol FC5_log_mnt00001
....
. その他すべてのホストで、物理ボリューム、ボリュームグループ、およびボリュームグループをスキャンします。


....
modprobe dm_mod
pvscan
vgscan
lvscan
....

NOTE: これらのコマンドでボリュームが見つからない場合は、再起動する必要があります。

論理ボリュームをマウントするには、論理ボリュームをアクティブ化する必要があります。ボリュームをアクティブ化するには、次のコマンドを実行します。

....
vgchange -a y
....


=== ファイルシステムの作成

すべてのデータおよびログ論理ボリュームと hana 共有 LUN に XFS ファイル システムを作成します。

....
mkfs.xfs FC5_data_mnt00001-vol
mkfs.xfs FC5_log_mnt00001-vol
mkfs.xfs /dev/mapper/svm1-FC5_shared
....

NOTE: 複数ホストのコマンド例には、 2+1 のマルチホスト HANA システムが示されています。



=== マウントポイントを作成する

必要なマウント ポイント ディレクトリを作成し、データベース ホストの権限を設定します。

....
sapcc-hana-tst:/ # mkdir -p /hana/data/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/log/FC5/mnt00001
sapcc-hana-tst:/ # mkdir -p /hana/shared
sapcc-hana-tst:/ # chmod –R 777 /hana/log/FC5
sapcc-hana-tst:/ # chmod –R 777 /hana/data/FC5
sapcc-hana-tst:/ # chmod 777 /hana/shared
....


=== ファイルシステムをマウント

システム起動中にファイルシステムをマウントするには、  `/etc/fstab`設定ファイルに必要なファイルシステムを追加し、  `/etc/fstab`設定ファイル:

....
# cat /etc/fstab
/dev/mapper/hana-FC5_shared /hana/shared xfs defaults 0 0
/dev/mapper/FC5_log_mnt00001-vol /hana/log/FC5/mnt00001 xfs relatime,inode64 0 0
/dev/mapper/FC5_data_mnt00001-vol /hana/data/FC5/mnt00001 xfs relatime,inode64 0 0
....

NOTE: データ LUN とログ LUN の XFS ファイルシステムは 'relatim' および inode64' マウントオプションを使用してマウントする必要があります

ファイルシステムをマウントするには、  `mount –a`ホストでコマンドを実行します。
