---
sidebar: sidebar 
permalink: bp/hana-fas-nfs-install-prep-nfsv4.html 
keywords: sap, hana, installation, preparations, nfsv4, user, authentication, storage, controller, hosts 
summary: NFS バージョン 4 以降では、ユーザ認証が必要です。この認証は、 Lightweight Directory Access Protocol （ LDAP ）サーバやローカルユーザアカウントなどの中央ユーザ管理ツールを使用して実行できます。 
---
= NFSv4 用の SAP HANA インストールの準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NFS バージョン 4 以降では、ユーザ認証が必要です。この認証は、 Lightweight Directory Access Protocol （ LDAP ）サーバやローカルユーザアカウントなどの中央ユーザ管理ツールを使用して実行できます。次のセクションでは、ローカルユーザアカウントを設定する方法について説明します。

管理ユーザ `<sid>adm`,`<sid>crypt`SAP HANAソフトウェアのインストールを開始する前に、SAP HANAホストとストレージコントローラにと `sapsys`グループを手動で作成する必要があります。



== SAP HANA ホスト

存在しない場合は、 SAP HANA ホストに「 sapsys 」グループを作成する必要があります。ストレージコントローラ上の既存のグループ ID と競合しない一意のグループ ID を選択する必要があります。

ユーザ `<sid>adm`と `<sid>crypt`がSAP HANAホストに作成されます。ストレージコントローラの既存のユーザIDと競合しない一意のIDを選択する必要があります。

マルチホストSAP HANAシステムの場合は、ユーザIDとグループIDがすべてのSAP HANAホストで同じである必要があります。グループとユーザは、および `/etc/passwd`の影響を受ける行をソースシステムから他のすべてのSAP HANAホストにコピーすることで、他のSAP HANAホストに作成され `/etc/group`ます。


NOTE: NFSv4 ドメインは、すべての Linux サーバ（ /etc/idmapd.conf ）と SVM で同じ値に設定する必要があります。Linux ホストの /etc/idmapd.conf ファイル内の domain パラメータ「 Domain=<domain-name> 」を設定します。

NFS IDMAPD サービスを有効にして開始します。

....
systemctl enable nfs-idmapd.service
systemctl start nfs-idmapd.service
....

NOTE: 最新の Linux カーネルでは、この手順は必要ありません。警告メッセージは無視してかまいません。



== ストレージコントローラ

ユーザIDとグループIDは、SAP HANAホストとストレージコントローラで同じである必要があります。グループとユーザは、ストレージクラスタで次のコマンドを入力することで作成されます。

....
vserver services unix-group create -vserver <vserver> -name <group name> -id <group id>
vserver services unix-user create -vserver <vserver> -user <user name> -id <user-id> -primary-gid <group id>
....
また、 SVM の UNIX ユーザルートのグループ ID を 0 に設定します。

....
vserver services unix-user modify -vserver <vserver> -user root -primary-gid 0
....