---
sidebar: sidebar 
permalink: bp/kvm-hana-introduction.html 
keywords: introduction,KVM, SAP HANA, tailored data center integration, FCP, NFS 
summary: このガイドでは、 NetAppストレージを使用して SUSE KVM for SAP HANA を構成する方法について説明します。 
---
= SUSE KVM とNetAppストレージを搭載した SAP HANA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このガイドでは、 NetAppストレージを使用して SUSE KVM for SAP HANA を構成する方法について説明します。

Marco Schoen 、ネットアップ



== はじめに

このドキュメントでは、 NetAppストレージを使用して SUSE KVM に導入された SAP HANA シングルホストに必要な追加手順について説明します。これは、 https://documentation.suse.com/sbp/sap-15/pdf/SBP-SLES4SAP-HANAonKVM-SLES15SP5_en.pdf["KVM 上の SAP HANA に関する SUSE ベストプラクティス"] 。

主に、KVM ホスト上で SR-IOV (シングル ルート I/O 仮想化) 用のネットワーク インターフェイスを構成する方法、これらの仮想インターフェイス (VF) を VM に割り当てる方法、および NFS を使用して SAP HANA のストレージにアクセスするために VM 内のインターフェイスを構成する方法を説明します。さらに、VM 内で SAP HANA を使用するために FCP を設定する方法についても説明します。


NOTE: SAP HANA ネットワーク通信および NFS を使用したストレージ アクセスには、SR-IOV を使用する必要があります。  FCP LUN を使用するには、物理 FCP HBA ポートを PCI デバイスとして VM に割り当てる必要があります。  SAP HANA マルチホスト システムはサポートされていません。



== 前提条件

このガイドは、KVM ホストとしての Linux Enterprise Server for SAP Applications 15 SP5/SP6 に有効です。 + 認定された SAP HANA サーバーとNetAppストレージを使用する必要があります。利用可能なオプションについては、SAP HANAハードウェアディレクトリを確認してください。 https://www.sap.com/dmc/exp/2014-09-02-hana-hardware/enEN[]

KVMホストとVMのセットアップと構成は、 https://documentation.suse.com/sbp/sap-15/pdf/SBP-SLES4SAP-HANAonKVM-SLES15SP5_en.pdf["KVM 上の SAP HANA に関する SUSE ベストプラクティス"] 。

サポートされているCPUアーキテクチャや制限事項などの最新情報については、SAP Note + を参照してください。https://me.sap.com/notes/3538596["3538596 - SUSE KVM 仮想化と SLES 15 SP5 を使用した SAP HANA - SAP for Me"]
