---
sidebar: sidebar 
permalink: bp/saphana-fas-nfs_host_setup.html 
keywords: host, setup, configuration, parameter, enterprise, suse, linux, subdirectories, create, mount, points, file, systems 
summary: このセクションで説明するすべての手順は、物理サーバ上の SAP HANA 環境と、 VMware vSphere 上で実行される SAP HANA 環境の両方で有効です。 
---
= ホストのセットアップ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
このセクションで説明するすべての手順は、物理サーバ上の SAP HANA 環境と、 VMware vSphere 上で実行される SAP HANA 環境の両方で有効です。



== SUSE Linux Enterprise Server の構成パラメータ

各 SAP HANA ホストでは、 SAP HANA によって生成されるワークロードに合わせて、追加のカーネルパラメータと構成パラメータを調整する必要があります。



=== SUSE Linux Enterprise Server 12 および 15

SUSE Linux Enterprise Server （ SLES ） 12 SP1 以降、カーネルパラメータは /etc/sysctl.d`d ディレクトリ内の構成ファイルで設定する必要があります。たとえば '91-NetApp-/hana.conf という名前の構成ファイルを作成する必要があります

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: SAP OS バージョン用の SLES に含まれている Saptune を使用してこれらの値を設定できます。を参照してください https://launchpad.support.sap.com/#/notes/3024346["SAP ノート 3024346"^] （ SAP ログインが必要です）。

。 `sunrpc.tcp_max_slot_table_entries` パラメータは次の場所で設定してください： `/etc/modprobe.d/sunrpc.conf`。ファイルが存在しない場合は、次の行を追加して先に作成する必要があります。

....
options sunrpc tcp_max_slot_table_entries=128
....


== Red Hat Enterprise Linux 7.2 以降の構成パラメータ

SAP HANA で生成されるワークロードに合わせて、各 SAP HANA ホストで追加のカーネルパラメータと構成パラメータを調整する必要があります。

。 `sunrpc.tcp_max_slot_table_entries` パラメータは次の場所で設定してください： `/etc/modprobe.d/sunrpc.conf`。ファイルが存在しない場合は、次の行を追加して先に作成する必要があります。

....
options sunrpc tcp_max_slot_table_entries=128
....
Red Hat Enterprise Linux 7.2 以降では、 /etc/sysctl.d` ディレクトリにある構成ファイルでカーネルパラメータを設定する必要があります。たとえば '91-NetApp-/hana.conf という名前の構成ファイルを作成する必要があります

....
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 131072 16777216
net.ipv4.tcp_wmem = 4096 16384  16777216
net.core.netdev_max_backlog = 300000
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
....

NOTE: Red Hat Enterprise Linuxバージョン8.6以降では、RHEL System Roles for SAP（Ansible）を使用してこれらの設定を適用することもできます。を参照してください https://launchpad.support.sap.com/#/notes/3024346["SAP ノート 3024346"^] （ SAP ログインが必要です）。



== /hana/shared ボリュームにサブディレクトリを作成します


NOTE: 以下の例は、 SID=NF2 の SAP HANA データベースを示しています。

必要なサブディレクトリを作成するには、次のいずれかの操作を行います。

* シングル・ホスト・システムの場合は '/hana/shared-volume をマウントし 'hared' サブディレクトリと usr-sap サブディレクトリを作成します


....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap
sapcc-hana-tst-06:mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....
* マルチ・ホスト・システムの場合は '/hana/shared-volume をマウントし ' 各ホストの 'hared' サブディレクトリと 'usr-sap' サブディレクトリを作成します
+
以下のコマンド例は、 2+1 のマルチホスト HANA システムを示しています。



....
sapcc-hana-tst-06:/mnt # mount <storage-hostname>:/NF2_shared /mnt/tmp
sapcc-hana-tst-06:/mnt # cd /mnt/tmp
sapcc-hana-tst-06:/mnt/tmp # mkdir shared
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host1
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host2
sapcc-hana-tst-06:/mnt/tmp # mkdir usr-sap-host3
sapcc-hana-tst-06:/mnt/tmp # cd ..
sapcc-hana-tst-06:/mnt # umount /mnt/tmp
....


== マウントポイントを作成する


NOTE: 以下の例は、 SID=NF2 の SAP HANA データベースを示しています。

必要なマウントポイントディレクトリを作成するには、次のいずれかの操作を行います。

* シングルホストシステムの場合は、マウントポイントを作成し、データベースホストに権限を設定します。


....
sapcc-hana-tst-06:/ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:/ # mkdir -p /hana/shared
sapcc-hana-tst-06:/ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/log/NF2
sapcc-hana-tst-06:/ # chmod –R 777 /hana/data/NF2
sapcc-hana-tst-06:/ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:/ # chmod -R 777 /usr/sap/NF2
....
* マルチホストシステムの場合は、マウントポイントを作成し、すべてのワーカーホストとスタンバイホストに権限を設定します。
+
以下のコマンド例は、 2+1 のマルチホスト HANA システムを示しています。

+
** 1 つ目のワーカーホスト：




....
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-06:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-06:~ # mkdir -p /hana/shared
sapcc-hana-tst-06:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-06:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-06:~ # chmod -R 777 /usr/sap/NF2
....
* 2 つ目のワーカーホスト：


....
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-07:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-07:~ # mkdir -p /hana/shared
sapcc-hana-tst-07:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-07:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-07:~ # chmod -R 777 /usr/sap/NF2
....
* スタンバイホスト：


....
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/data/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00001
sapcc-hana-tst-08:~ # mkdir -p /hana/log/NF2/mnt00002
sapcc-hana-tst-08:~ # mkdir -p /hana/shared
sapcc-hana-tst-08:~ # mkdir -p /usr/sap/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/log/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/data/NF2
sapcc-hana-tst-08:~ # chmod -R 777 /hana/shared
sapcc-hana-tst-08:~ # chmod -R 777 /usr/sap/NF2
....


== ファイルシステムをマウント

NFSのバージョンとONTAP のリリースに応じて、異なるマウントオプションが使用されます。次のファイルシステムをホストにマウントする必要があります。

* 「 /hana/data/sid/mnt0000* 」と入力します
* 「 /hana/log/sid/mnt0000* 」と入力します
* 「 /hana/shared 」
* /usr/sap/SID


次の表に、シングルホスト SAP HANA データベースとマルチホスト SAP HANA データベースのファイルシステムごとに使用する必要がある NFS のバージョンを示します。

|===
| ファイルシステム | SAP HANA シングルホスト | SAP HANA マルチホスト 


| /hana/data/sid/mnt0000* | NFSv3 または NFSv4 | NFSv4 


| /hana/log/sid/mnt0000* | NFSv3 または NFSv4 | NFSv4 


| /hana/shared にアクセスします | NFSv3 または NFSv4 | NFSv3 または NFSv4 


| /usr/sap/SID | NFSv3 または NFSv4 | NFSv3 または NFSv4 
|===
次の表に、 NFS の各バージョンと ONTAP のリリースのマウントオプションを示します。共通パラメータは、 NFS と ONTAP のバージョンには依存しません。


NOTE: SAP LaMa では、 /usr/sap/SID ディレクトリをローカルにする必要があります。したがって、 SAP LaMa を使用している場合は、 /usr/sap/SID の NFS ボリュームをマウントしないでください。

NFSv3 では、ソフトウェアまたはサーバに障害が発生した場合に NFS ロックのクリーンアップ処理が行われないようにするため、 NFS ロックをオフにする必要があります。

ONTAP 9 では、 NFS 転送サイズを最大 1MB に設定できます。具体的には、 40GbE 以上でのストレージシステムへの接続では、スループットの期待値を達成するために転送サイズを 1MB に設定する必要があります。

|===
| 共通パラメータ | NFSv3 | NFSv4 | ONTAP 9 での NFS 転送サイズ | ONTAP 8 での NFS 転送サイズ 


| rw 、 bg 、 hard 、 timeo = 600 、 noatime 、 | nfsvers = 3、nolock、 | nfsvers = 4.1、ロック | rsize=1048576 、 wsize=262144 、 | rsize=65536 、 wsize=65536 、 
|===

NOTE: NFSv3 の読み取りパフォーマンスを向上させるには、「 nConnect=n 」マウントオプションを使用することを推奨します。このオプションは、 SUSE Linux Enterprise Server 12 SP4 以降および RedHat Enterprise Linux （ RHEL ） 8.3 以降で使用できます。


NOTE: パフォーマンステストによると、 `nconnect=4` 特にデータボリュームに対して良好な読み取り結果が得られます。ログへの書き込みは、次のようなセッション数が少ないことでメリットが得られる場合があります。 `nconnect=2`。「nConnect」オプションを使用すると、共有ボリュームにもメリットがあります。NFS サーバからの最初のマウント（ IP アドレス）では、使用されるセッションの量が定義されることに注意してください。同じIPアドレスにさらにマウントしても、nConnectに別の値が使用されていても、この値は変更されません。


NOTE: ONTAP 9.8およびSUSE SLES15SP2以降、またはRed Hat RHEL 8.4以降では、ネットアップはNFSv4.1のnConnectオプションもサポートしています。


NOTE: nconnectをNFSv4.xで使用する場合は、次のルールに従ってNFSv4.xセッションスロットの数を調整する必要があります。
セッションスロットの数は<nconnect value> x 64に等しくなります。
主催者でこれは次のように審査されます。
`echo options nfs max_session_slots= <calculated value> > /etc/modprobe.d/nfsclient.conf`
再起動します。サーバー側の値も調整する必要があります。で説明されているように、セッションスロットの数を設定します。 link:saphana-fas-nfs_storage_controller_setup.html#nfs-configuration-for-nfsv4["NFSv4 の NFS 設定"]

/etc/fstab 構成ファイルを使用してシステムのブート中にファイル・システムをマウントするには ' 次の手順を実行します

次の例は、 SID=NF2 で、 NFSv3 を使用し、書き込みの場合は NFS 転送サイズが 1MB 、読み取りの場合は 256K の、シングルホスト SAP HANA データベースを示しています。

. 必要なファイル・システムを /etc/fstab 構成ファイルに追加します
+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=3,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/usr-sap /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data01>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Run `ount – a を実行して、すべてのホストのファイルシステムをマウントします。


次の例は、 SID=NF2 で、データファイルシステムとログファイルシステムに NFSv4.1 を使用し、「 /hana/shared 」ファイルシステムと「 /usr/sap/nf2 」ファイルシステムに NFSv3 を使用する、マルチホスト SAP HANA データベースを示しています。書き込みでは、読み取りの場合は 1MB 、書き込みの場合は 256K の NFS 転送サイズが使用されます。

. 必要なファイル・システムを ' すべてのホスト上の /etc/fstab 構成ファイルに追加します
+

NOTE: 。 `/usr/sap/NF2` ファイルシステムはデータベースホストごとに異なります。次の例は、 `/NF2_shared/usr-sap-host1`。

+
....
sapcc-hana-tst-06:/ # cat /etc/fstab
<storage-vif-data01>:/NF2_data_mnt00001 /hana/data/NF2/mnt00001 nfs  rw,nfsvers=4.1,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_data_mnt00002 /hana/data/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log01>:/NF2_log_mnt00001 /hana/log/NF2/mnt00001 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-log02>:/NF2_log_mnt00002 /hana/log/NF2/mnt00002 nfs rw,nfsvers=4.1,hard,timeo=600,nconnect=2,rsize=1048576,wsize=262144,bg,noatime,lock 0 0
<storage-vif-data02>:/NF2_shared/usr-sap-host1 /usr/sap/NF2 nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
<storage-vif-data02>:/NF2_shared/shared /hana/shared nfs rw,nfsvers=3,hard,timeo=600,nconnect=4,rsize=1048576,wsize=262144,bg,noatime,nolock 0 0
....
. Run `ount – a を実行して、すべてのホストのファイルシステムをマウントします。

