---
sidebar: sidebar 
permalink: lifecycle/libelle-sc-overview.html 
keywords: tr4929, 4929, overview, introduction 
summary: SAPのライフサイクル管理を最適化するネットアップのソリューションは、SAP AnyDBとSAP HANAデータベースに統合されています。さらに、ネットアップは、アプリケーションと統合された効率的なデータ保護と、SAPテストシステムの柔軟なプロビジョニングを組み合わせた、SAPのライフサイクル管理ツールに統合しています。 
---
= TR-4929：Libelle SystemCopyによるSAPシステムのコピー処理の自動化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Holger Zecha、Tobias Brandl、ネットアップFranz Diegruber、Libelle

今日のダイナミックなビジネス環境では、企業は継続的なイノベーションを提供し、変化する市場に迅速に対応する必要があります。このような競争の激しい状況下で、業務プロセスの柔軟性を高める企業は、市場の需要に効果的に対応できます。

市場ニーズの変化は、企業のSAP環境にも影響を及ぼし、定期的な統合、変更、更新が必要になります。IT部門は、これらの変更を、より少ないリソースでより短い期間で実装する必要があります。変更を導入する際のリスクを最小限に抑えるには、本番環境の実際のデータを使用するSAPシステムを追加で必要とする、テストとトレーニングを徹底的に実施する必要があります。

従来のSAPライフサイクル管理アプローチでは、このようなシステムは主に手動プロセスに基づいてプロビジョニングされます。このような手動プロセスは、ミスを避けられず、時間もかかることが多く、イノベーションの遅れやビジネス要件への対応の遅れにつながります。

SAPのライフサイクル管理を最適化するネットアップのソリューションは、SAP AnyDBとSAP HANAデータベースに統合されています。さらに、ネットアップは、アプリケーションと統合された効率的なデータ保護と、SAPテストシステムの柔軟なプロビジョニングを組み合わせた、SAPのライフサイクル管理ツールに統合しています。

このようなネットアップのソリューションは、大規模なデータベースでも膨大なデータを効率的に管理するという問題 を解決しますが、SAPシステムの完全なエンドツーエンドのコピーおよび更新処理には、ソースSAPシステムのIDをターゲットシステムに完全に変更するためのコピー前処理とコピー後処理が含まれている必要があります。SAPでは、で必要なアクティビティについて説明します https://help.sap.com/viewer/6ffd9a3438944dc39dfe288d758a2ed5/LATEST/en-US/f6abb90a62aa4695bb96871a89287704.html["SAP同種システムのコピーガイド"^]。ネットアップのパートナー様は、手動プロセスの回数をさらに減らし、SAPシステムのコピープロセスの品質と安定性を高めるために https://www.libelle.com["Libelle"^] を開発しました https://www.libelle.com/products/systemcopy["Libelle SystemCopy (LSC)"^] ツール。Libelleと共同で、SAPシステムコピー用のネットアップソリューションをLSCに統合して提供しています https://www.youtube.com/watch?v=wAFyA_WbNm4["完全なエンドツーエンドの自動システムコピーを、記録的な時間で作成します"^]。



== アプリケーションに統合されたSnapshotコピー処理

アプリケーションと整合性のあるNetApp Snapshotコピーをストレージレイヤに作成する機能は、本ドキュメントで説明するシステムコピー処理とシステムクローン処理の基盤となります。ストレージベースのSnapshotコピーは、ネットアップのSnapCenter Plug-in for SAP HANAまたはSAPのネイティブONTAP システム上の任意のDBを使用して作成されます https://docs.microsoft.com/en-us/azure/azure-netapp-files/azacsnap-introduction["Microsoft Azure Application Consistent Snapshotツール"^] （AzAcSnap）、およびMicrosoft Azureで実行されるSAP HANAとOracleデータベースによって提供されるインターフェイス。SAP HANAを使用している場合は、SnapCenter とAzAcSnapがSnapshotコピーをSAP HANAバックアップカタログに登録することで、リストアとリカバリ、およびクローニング処理に使用できます。



== オフサイトバックアップやディザスタリカバリのデータレプリケーションを実行できます

アプリケーションと整合性のあるSnapshotコピーは、ストレージレイヤから、オンプレミスのSnapCenter で制御されるオフサイトのバックアップサイトやディザスタリカバリサイトにレプリケートできます。レプリケーションはブロック変更に基づいているため、スペースと帯域幅を効率的に使用できます。クロスリージョンレプリケーション（CRR）機能を使用してAzureリージョン間でAzure NetApp Files ボリュームを効率的にレプリケートすることで、AzureでAzure NetApp Files 実行されているSAP HANAシステムとOracleシステムにも同じテクノロジが使用されます。



== SAPシステムのコピー処理やクローニング処理には、任意のSnapshotコピーを使用できます

ネットアップのテクノロジとソフトウェアの統合により、ソースシステムの任意のSnapshotコピーを使用してSAPシステムのコピーやクローニングを実行できます。このSnapshotコピーは、SAP本番用システムと同じストレージ、オフサイトのバックアップに使用するストレージ（AzureのAzure NetApp Files バックアップなど）、またはディザスタリカバリサイトのストレージ（Azure NetApp Files CRRターゲットボリューム）のいずれかから選択できます。この柔軟性により、必要に応じて開発用システムとテスト用システムを本番用システムと分離し、ディザスタリカバリサイトでのディザスタリカバリのテストなど、さまざまなシナリオに対応することができます。



== 統合による自動化

SAPテストシステムのプロビジョニングにはさまざまなシナリオとユースケースがあり、自動化のレベルに関してもさまざまな要件が存在する場合があります。ネットアップのSAP向けソフトウェア製品は、SAPなどのサードパーティベンダーが提供するデータベースやライフサイクル管理製品（Libelleなど）と統合されており、さまざまなシナリオや自動化のレベルをサポートします。

SAP HANAとSAP AnyDBまたはAzure上のAzAcSnap向けのプラグインを備えたNetApp SnapCenter を使用して、アプリケーションと整合性のあるSnapshotコピーに基づいて必要なストレージボリュームのクローンをプロビジョニングし、開始されたSAPデータベースまで、必要なホストとデータベースのすべての処理を実行できます。SAPシステムのコピー、システムクローン、システムの更新、SAPのポストプロセスなどの追加の手動手順が必要になる場合があります。詳細については、次のセクションで説明します。

完全に自動化されたエンドツーエンドのSAPテストシステムのプロビジョニングまたは更新は、Libelle SystemCopy（LSC）自動化を使用して実行できます。SnapCenter またはAzAcSnapのLSCへの統合については、このドキュメントで詳しく説明します。



== Libelle SystemCopy

Libelle SystemCopyは、完全に自動化されたシステムコピーとランドスケープコピーを作成するフレームワークベースのソフトウェア解決策 です。ボタンを口頭で操作することで、QAおよびテストシステムを新しい本番データで更新できます。Libelle SystemCopyは、従来のすべてのデータベースとオペレーティングシステムをサポートし、すべてのプラットフォームに独自のコピーメカニズムを提供しますが、同時にバックアップ/リストア手順や、NetApp SnapshotコピーやNetApp FlexCloneボリュームなどのストレージツールを統合します。システムのコピー中に必要なアクティビティは、SAP ABAPスタックの外部から制御されます。そのため、SAPアプリケーションでは転送などの変更は必要ありません。一般に、システムコピー手順 を正常に完了するために必要な手順は、次の4つに分類できます。

* *確認フェーズ。*関係するシステム環境を確認してください。
* *プリフェーズ*システムコピーのターゲット・システムを準備します。
* *コピーフェーズ*ソースからターゲット・システムに実際の本番データベースのコピーを提供します
* *ポスト・フェーズ*：コピー後のすべてのタスクで同機種システムのコピー手順 を完了し'ターゲット・システムを更新します


コピーフェーズでは、NetApp SnapshotとFlexCloneの機能を使用して、最大のデータベースであっても、必要な時間を数分に短縮できます。

チェックフェーズ、プリフェーズ、およびポストフェーズの場合、LSCには、一般的な更新操作の95%をカバーする450以上の事前設定されたタスクが付属しています。その結果、LSCはSAP標準に従って自動化を推進します。LSCはソフトウェアで定義されるため、システム更新プロセスを簡単に調整および拡張して、お客様のSAP環境固有のニーズに対応できます。



== SAPシステムの更新とクローニングのユースケース

ソースシステムのデータをターゲットシステムで使用できるようにする必要があるシナリオは複数あります。

* 品質保証およびテストおよびトレーニングシステムの定期的な更新
* 論理的な破損に対処するために、システム環境の障害修復または修復を行う
* ディザスタリカバリのテストシナリオ


修復システムと災害復旧テストシステムは、通常、更新されたテストおよびトレーニングシステムのためにSAPシステムクローン（広範囲な後処理操作は不要）を使用して提供されますが、これらの後処理手順を適用してソースシステムと共存させる必要があります。そのため、本ドキュメントでは、SAPシステムの更新シナリオに焦点を当てて説明します。さまざまなユースケースの詳細については、テクニカルレポートを参照してください https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf["TR-4667：『Automating SAP HANA System Copy and Clone Operations with SnapCenter 』"^]。

このドキュメントの残りの部分は、2つの部分に分かれています。最初のパートでは、オンプレミスのNetApp ONTAP システムで実行されているSAP HANAシステムとSAP AnyDBシステム向けのNetApp SnapCenter とLibelle SystemCopyの統合について説明します。2番目のパートでは、Microsoft Azureで実行されているSAP HANAシステム用のLSCと、提供されているAzure NetApp Files とのAzAcSnapの統合について説明します。ONTAP テクノロジの基盤は同じですが、Azure NetApp Files は、ネイティブONTAP インストールとは異なるインターフェイスとツールの統合（AzAcSnapなど）を提供します。

link:libelle-sc-sap-hana-system-refresh-with-lsc-and-snapcenter.html["次の例：LSCとSnapCenter でSAP HANAシステムが更新されます。"]
