---
sidebar: sidebar 
permalink: lifecycle/sc-copy-clone-supported-infrastructure.html 
keywords: tr4667, 4667, SAP HANA, cloning, system refresh 
summary: SAPのライフサイクル管理を最適化するNetAppソリューションは、SAP HANAデータベースとライフサイクル管理ツールに統合されており、効率的なアプリケーション統合データプロテクションと、SAPテストシステムの柔軟なプロビジョニングが組み合わされています。 
---
= サポートされるインフラとシナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このドキュメントでは、オンプレミスのNetAppシステム、Amazon FSx for NetApp ONTAPシステム、およびAzure NetApp Filesで実行されるSAP HANAシステムの更新とクローニングのシナリオについて説明します。ただし、すべてのストレージプラットフォームですべての機能とシナリオを使用できるわけではありません。次の表は、サポートされる構成をまとめたものです。

このドキュメントでは、オンプレミスのNetAppシステムで実行されるSAP HANAランドスケープを使用し、NFSをストレージプロトコルとして使用しています。ワークフローの手順のほとんどは、プラットフォームごとに同じです。違いがある場合は、このドキュメントで説明します。

[cols="25%,25%,25%,25%"]
|===
|  | *オンプレミスのNetAppシステム* | * AWS FSx for NetApp ONTAP * | * Azure NetApp Files * 


| ストレージプロトコルとファイルシステム | ベアメタル：NFS、XFSを使用したFC VMware：ゲスト内マウントのNFS、VMDKおよびXFSを使用したFC | NFS | NFS 


| シンクローン（FlexClone） | はい。 | はい。 | はい。ただしSnapCenterには統合されていません。 


| クローンスプリット処理 | はい。 | はい。 | はい。ただしSnapCenterには統合されていません。 


| フライマリカラノクロニンク | はい。 | はい。 | はい。 


| オフサイトバックアップからのクローニング | はい。 | はい。 | はい、ANFバックアップから新しいボリュームにリストアします 


| DRサイトでのクローニング | はい。 | はい。 | はい。ただしSnapCenterには統合されていません。 
|===
VMware VMFSおよびNetApp ASAr2システムを使用したHANAのSAPシステムリフレッシュ操作に関する追加情報については、 https://docs.netapp.com/us-en/netapp-solutions-sap/backup/hana-sc-vmfs-asar2sap-refresh.html["SAP システムリフレッシュ"]を参照してください。
